CREATE TABLE IF NOT EXISTS public.products (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	category varchar(255) NULL,
	code varchar(255) NOT NULL,
	created_at int8 NOT NULL,
	description varchar(2000) NULL,
	image varchar(255) NULL,
	internal_reference varchar(255) NULL,
	inventory_status varchar(255) NULL,
	"name" varchar(255) NOT NULL,
	price float8 NOT NULL,
	quantity int4 NULL,
	rating float8 NULL,
	shell_id int8 NULL,
	updated_at int8 NOT NULL,
	CONSTRAINT products_inventory_status_check CHECK (((inventory_status)::text = ANY ((ARRAY['INSTOCK'::character varying, 'LOWSTOCK'::character varying, 'OUTOFSTOCK'::character varying])::text[]))),
	CONSTRAINT products_pkey PRIMARY KEY (id),
	CONSTRAINT uk57ivhy5aj3qfmdvl6vxdfjs4p UNIQUE (code)
);