CREATE TABLE IF NOT EXISTS public.cart_item (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at int8 NOT NULL,
	quantity int4 NOT NULL,
	updated_at int8 NOT NULL,
	product_id int8 NOT NULL,
	user_id int8 NOT NULL,
	CONSTRAINT cart_item_pkey PRIMARY KEY (id),
	CONSTRAINT uc_cart_user_product UNIQUE (user_id, product_id)
);